### login admin
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login vip
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "vip@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### login user
POST http://localhost:8080/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "user@gmail.com",
  "password": "password"
}

> {%
    client.global.set("auth_token", "Bearer " + response.body.token);
%}

### test
POST http://localhost:8080/api/v1/rentals
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get rentals by user id
GET http://localhost:8080/api/v1/rentals/1
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

### get all rentals
GET http://localhost:8080/api/v1/rentals
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

##### get all rentals
##GET http://localhost:8080/api/v1/rentals?page=2&size=3
##Accept: application/json
##Content-Type: application/json
##Authorization: {{auth_token}}
#
### rent bicycle
POST http://localhost:8080/api/v1/rentals/rent
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "bicycleId": "bike1",
  "userId": 1
}

### return bicycle
POST http://localhost:8080/api/v1/rentals/return
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "bicycleId": "bike1",
  "userId": 1
}

### create reservation
POST http://localhost:8080/api/v1/rentals
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "userId": 3
}